//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public long rent_id { get; set; }
        public long tenant_id { get; set; }
        public long mall_id { get; set; }
        public string pavilion_number { get; set; }
        public long employee_id { get; set; }
        public long status_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Pavilion Pavilion { get; set; }
        public virtual Rent_statuses Rent_statuses { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
