//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilion()
        {
            this.Rent = new HashSet<Rent>();
        }
    
        public long mall_id { get; set; }
        public string pavilion_number { get; set; }
        public int floor { get; set; }
        public long status_id { get; set; }
        public double square { get; set; }
        public double cost_per_square_meter { get; set; }
        public double value_added_factor { get; set; }
    
        public virtual Mall Mall { get; set; }
        public virtual Pavilion_statuses Pavilion_statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
